#!/usr/bin/env python3 

import os, sys
import argparse


tables = [
    '_voided_edges',
    '_voided_nodes',
    'edge_adverseeventatevaluationevaluation',
    'edge_adverseeventhadadverseeventcase',
    'edge_adverseeventnextadverseevent',
    'edge_adverseeventofagentagent',
    'edge_adverseeventrelatestocase',
    'edge_agentadministrationofagentagent',
    'edge_agentadministrationonvisitvisit',
    'edge_agentofstudyarmstudyarm',
    'edge_aliquotmemberofsample',
    'edge_aliquotrelatestocase',
    'edge_assayofsamplesample',
    'edge_assayrelatestocase',
    'edge_casememberofcohort',
    'edge_cohortmemberofexperiment',
    'edge_cohortmemberofstudyarm',
    'edge_cycleofcasecase',
    'edge_datareleasedescribesroot',
    'edge_datareleaserelatestocase',
    'edge_demographicofcasecase',
    'edge_demographicrelatestocase',
    'edge_diagnosisofcasecase',
    'edge_diagnosisrelatestocase',
    'edge_diseaseextentatevaluationevaluation',
    'edge_diseaseextentrelatestocase',
    'edge_enrollmentofcasecase',
    'edge_evaluationonvisitvisit',
    'edge_evaluationrelatestocase',
    'edge_experimentmemberofproject',
    'edge_experimentmemberofstudyarm',
    'edge_fileofassayassay',
    'edge_filerelatestocase',
    'edge_followupofcasecase',
    'edge_followuprelatestocase',
    'edge_imageofassayassay',
    'edge_imagerelatestocase',
    'edge_labexamatevaluationevaluation',
    'edge_labexamrelatestocase',
    'edge_offstudyrelatestocase',
    'edge_offstudywentoffstudycase',
    'edge_offtreatmentrelatestocase',
    'edge_offtreatmentwentofftreatmentcase',
    'edge_physicalexamatenrollmentenrollment',
    'edge_physicalexamatevaluationevaluation',
    'edge_physicalexamrelatestocase',
    'edge_principalinvestigatorofstudystudy',
    'edge_priorsurgeryatenrollmentenrollment',
    'edge_priorsurgerynextpriorsurgery',
    'edge_priorsurgeryrelatestocase',
    'edge_priortherapyatenrollmentenrollment',
    'edge_priortherapynextpriortherapy',
    'edge_priortherapyrelatestocase',
    'edge_projectmemberofprogram',
    'edge_rootrelatestocase',
    'edge_samplememberofcase',
    'edge_samplenextsample',
    'edge_sampleonvisitvisit',
    'edge_samplerelatestocase',
    'edge_studyarmmemberofstudy',
    'edge_studymemberofproject',
    'edge_studysiteofstudystudy',
    'edge_visitnextvisit',
    'edge_visitofcyclecycle',
    'edge_visitrelatestocase',
    'edge_vitalsignsatevaluationevaluation',
    'edge_vitalsignsrelatestocase',
    'node_adverseevent',
    'node_agent',
    'node_agentadministration',
    'node_aliquot',
    'node_assay',
    'node_case',
    'node_cohort',
    'node_cycle',
    'node_datarelease',
    'node_demographic',
    'node_diagnosis',
    'node_diseaseextent',
    'node_enrollment',
    'node_evaluation',
    'node_experiment',
    'node_file',
    'node_followup',
    'node_image',
    'node_labexam',
    'node_offstudy',
    'node_offtreatment',
    'node_physicalexam',
    'node_principalinvestigator',
    'node_priorsurgery',
    'node_priortherapy',
    'node_program',
    'node_project',
    'node_root',
    'node_sample',
    'node_study',
    'node_studyarm',
    'node_studysite',
    'node_visit',
    'node_vitalsigns',
    'transaction_documents',
    'transaction_logs',
    'transaction_snapshots'
]

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Export GEN3 PostgreSQL database into csv files')
    parser.add_argument('db', help='an integer for the accumulator')
    parser.add_argument('dir', help='Output directory')
    parser.add_argument('user', help='PostgreSQL user name', nargs='?', default='postgres')

    args = parser.parse_args()
    os.system('mkdir -p {}'.format(args.dir))

    for table in tables:
        print(table)
        os.system("psql -U {1} {2} -c \"\\copy public.{0} to '{3}/{0}.csv' delimiter ',' csv header;\"".format(table, args.user, args.db, args.dir))
