  temp_folder: tmp
  backup_folder: /tmp/data-loader-backups

  # character used to separate relationship properties from relationship names
  rel_prop_delimiter: $

  neo4j:
    # Location of Neo4j server, e.g., bolt://127.0.0.1:7687, can be overridden by -i/--uir argument
    uri: bolt://127.0.0.1:7687
    # Neo4j username, can be overridden by -u/--user argument
    user: neo4j
    # Neo4j password, can be overridden by -p/--password argument, and environment variable NEO_PASSWORD
    password: your_neo4j_password

  # Schema files' locations, usually two file, can be overridden by -s/--schema argument
  schema:
    - tests/data/icdc-model.yml
    - tests/data/icdc-model-props.yml

  # Property file location, props-icdc.yml, props-ctdc.yml etc. can be overridden by --prop-file argument
  prop_file: config/props-icdc.yml

  # Skip validations, aka. Cheat Mode, can be overridden by -c/--cheat-mode argument
  cheat_mode: false
  # Validations only, skip loading, can be overridden by -d/--dry-run argument
  dry_run: false
  # Wipe clean database before loading, you'll lose all data!, can be overridden by --wipe-db argument
  wipe_db: false
  # Skip backup database step, can be overridden by --no-backup argument
  no_backup: false
  # Automatically confirm deletion and database wiping, without asking user to confirm, can be overridden by -y/--yes argument
  no_confirmation: false
  # Max violations to display, default is 10, can be overridden by -M/--max-violations argument
  max_violations: 10
  #Disable saving parent IDs in children
  no_parents: false

  # S3 bucket name, if you are loading from an S3 bucket, can be overridden by -b/--bucket argument
  s3_bucket:
  # S3 folder for dataset, will be overridden by --s3-folder argument
  s3_folder:
  # Loading mode, can be UPSERT_MODE, NEW_MODE or DELETE_MODE, default is UPSERT_MODE, can be overridden by -m/--mode argument
  loading_mode: UPSERT_MODE
  # Location of dataset, can be overridden by --dataset argument
  dataset: tests/data/Dataset


