Config:
  temp_folder: tmp
  backup_folder: /tmp/data-loader-backups

  neo4j:
    # Location of Neo4j server, e.g., bolt://127.0.0.1:7687, can be overridden by -i/--uir argument
    uri: bolt://127.0.0.1:7687
    # Neo4j username, can be overridden by -u/--user argument
    user: neo4j
    # Neo4j password, if not set here, will try to read from environment variable NEO_PASSWORD. CLI argument -p/--password will overwrite either settings
    password: # your_neo4j_password

  # Schema files' locations, usually two file, can be overridden by -s/--schema argument
  schema:
    - tests/data/icdc-model.yml
    - tests/data/icdc-model-props.yml

  # Plugin can be used to create additional nodes and relationships
  plugins:
    - module: loader_plugins.visit_creator
      class: VisitCreator

    - module: loader_plugins.individual_creator
      class: IndividualCreator

    - moduel: moduel_name_2
      class: clase_name_2
      params:
        param_1: value_1
        param_2: value_2

  # Property file location, props-icdc.yml, props-ctdc.yml etc. can be overridden by --prop-file argument
  prop_file: config/props-icdc-pmvp.yml

  # Skip validations, aka. Cheat Mode, can be overridden by -c/--cheat-mode argument
  cheat_mode: false
  # Validations only, skip loading, can be overridden by -d/--dry-run argument
  dry_run: false
  # Wipe clean database before loading, you'll lose all data!, can be overridden by --wipe-db argument
  wipe_db: false
  # Skip backup database step, can be overridden by --no-backup argument
  no_backup: false
  # Automatically confirm deletion and database wiping, without asking user to confirm, can be overridden by -y/--yes argument
  no_confirmation: false
  # Max violations to display, default is 10, can be overridden by -M/--max-violations argument
  max_violations: 10
  # Split the loading transaction into separate transactions for each file
  split_transactions: false
  # Database type, can be either neo4j or memgraph
  database_type: memgraph
  # The snapshot folder directory, will be None if not provided
  memgraph_snapshot_dir: /var/lib/memgraph/snapshots

  # S3 bucket name, if you are loading from an S3 bucket, can be overridden by -b/--bucket argument
  s3_bucket:
  # S3 folder for dataset, will be overridden by --s3-folder argument
  s3_folder:
  # Loading mode, can be "upsert", "new" or "delete", default is "upsert", can be overridden by -m/--mode argument
  loading_mode: upsert
  # Location of dataset, can be overridden by --dataset argument
  dataset: tests/data/Dataset
  # destination dir to upload log file. Two options: 1) local dir 2) s3 bucket dir start with 's3://''
  # s3://[bucket]/[folder1/forlder2/...]
  upload_log_dir: