Config:
  # Neo4j URL with port number
  neo4j_uri: "bolt://127.0.0.1:7687"
  # Neo4j user name, default is neo4j
  neo4j_user: neo4j
  # Password for Neo4j user
  neo4j_password: neo4j_password
  # Elastic search host name or IP, without trailing slash
  es_host: localhost
  # Path to about file
  about_file: path_to_about_yaml_file

  model_files:
    - bento-model/model-desc/bento_tailorx_model_file.yaml
    - bento-model/model-desc/bento_tailorx_model_properties.yaml

  prop_file: config/props-bento-ext.yml
