# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: CRDC Data Loader
prefect-version: 2.14.10

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
  - prefect.deployments.steps.git_clone:
      #id: clone-step
      repository: https://github.com/CBIIT/icdc-dataloader.git
      branch: 3.2.0_hub
      include_submodules: True
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/CBIIT/CCDI-Inventory-Dataloader.git
      branch: 2.8.0_Opensearch_Loader
      include_submodules: True
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/CBIIT/cds-model.git
      branch: 3.1.0
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/CBIIT/icdc-model-tool.git
      branch: master
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/CBIIT/bento-cds-backend.git
      branch: 3.1.0_less_page
      include_submodules: True
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/CBIIT/bento-cds-frontend.git
      branch: 4.6.0
      include_submodules: True
  - prefect.deployments.steps.set_working_directory:
      directory: "/opt/prefect/icdc-dataloader-3.2.0_hub"
  - prefect.projects.steps.pip_install_requirements:
      requirements_file: requirements.txt
      directory: "{{ clone-step.directory }}"
      stream_output: False

# the deployments section allows you to provide configuration for deploying flows
deployments:
  - name: data-hub-opensearch-loader
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint: es_loader_from_neo4j_prefect.py:es_loader_prefect
    parameters:
      environment: "dev"
      about_file: "../bento-cds-frontend/src/content/prod/aboutPagesContent.yaml"
      indices_list: [  "cohorts",  "study_participants",  "participants",  "survivals",  "treatments",  "treatment_responses",  "diagnosis",  "studies",  "samples",  "files",  "model_nodes",  "model_properties",  "model_values",  "ccdi_hub_static_pages"]
      indices_file: "../CCDI-Inventory-Dataloader/config/es_indices_ccdi_model.yml"
      model_files:
        - ../ccdi-model/model-desc/ccdi-model.yml
        - ../ccdi-model/model-desc/ccdi-model-props.yml
      prop_file: "../CCDI-Inventory-Dataloader/config/props-ccdi-model.yml"
    work_pool:
      name: ccdi-curation-8gb
      work_queue_name: ccdi-esloader-queue
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "ESLoader"