# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: C3DC Data Loader
prefect-version: null

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
  - prefect.deployments.steps.git_clone:
      #id: clone-step
      repository: https://github.com/CBIIT/icdc-dataloader.git
      branch: 3.2.0_c3dc
      include_submodules: True
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/CBIIT/icdc-model-tool.git
      branch: master
  - prefect.deployments.steps.set_working_directory:
      directory: "/opt/prefect/icdc-dataloader-3.2.0"
  - prefect.deployments.steps.pip_install_requirements:
      requirements_file: requirements.txt
      directory: "{{ clone-step.directory }}"
      stream_output: False

# the deployments section allows you to provide configuration for deploying flows
deployments:
  - name: c3dc-opensearch-loader
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint: es_loader_prefect.py:es_loader_prefect
    parameters:
      indices_list: []
      about_file: "config/searchablePagesContent.yaml"
      indices_file: "config/es_indices_c3dc.yml"
      prop_file: config/props-c3dc.yml
    work_pool:
      name: ccdi-c3dc-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "ESLoader"
