database_type:
  - neo4j
  - memgraph
environments:
  dev: "ctdc_memgraph_secret_name_dev"
  dev2: "ctdc_secret_name_dev2"
model_repo_url: "https://github.com/CBIIT/ctdc-model.git"
backend_repo_url: "https://github.com/CBIIT/crdc-ctdc-backend.git"
frontend_repo_url: "https://github.com/CBIIT/crdc-ctdc-ui.git"