database_type:
  - neo4j
  - memgraph
environments:
  dev: "cds_secret_name_dev"
  dev2: "cds_secret_name_dev2"
  dev_cdk: "gc_memgraph_secret_name_dev_cdk"
model_repo_url: "https://github.com/CBIIT/cds-model.git"
backend_repo_url: "https://github.com/CBIIT/bento-cds-backend.git"
frontend_repo_url: "https://github.com/CBIIT/bento-cds-frontend.git"