database_type:
  - neo4j
  - memgraph
environments: "neo4j-dev-creds"
model_repo_url: "https://github.com/CBIIT/C3DC-model.git"
backend_repo_url: "https://github.com/CBIIT/CCDI-C3DC-Dataloader.git"
frontend_repo_url: "https://github.com/CBIIT/CCDI-C3DC-Dataloader.git"